apiVersion: v1
kind: Service
metadata:
  name: my-go-app
spec:
  selector:
    app: my-go-app
  ports:
    - protocol: TCP
      port: 8080 # 对外暴露的端口
      targetPort: 8080 # 容器内部的端口
      nodePort: 30984 # 外部访问的端口（可以手动指定）
  type: NodePort  # 使用 NodePort 将服务暴露给集群外部


